export const ADD_PRODUCT = 'ADD_PRODUCT';
export const SUCCESS_ADD_PRODUCT = 'SUCCESS_ADD_PRODUCT';
export const FAILURE_ADD_PRODUCT = 'FAILURE_ADD_PRODUCT';

export const START_PRODUCTS_DOWNLOAD = 'START_PRODUCT_DOWNLOAD';
export const SUCCESS_PRODUCTS_DOWNLOAD = 'SUCCESS_PRODUCT_DOWNLOAD';
export const FAILURE_PRODUCTS_DOWNLOAD = 'FAILURE_PRODUCT_DOWNLOAD';

export const GET_PRODUCT_DELETE = 'GET_DELETE_PRODUCT';
export const SUCCESS_PRODUCT_DELETE = 'SUCCESS_DELETE_PRODUCT';
export const FAILURE_PRODUCT_DELETE = 'FAILURE_DELETE_PRODUCT';