export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE';

export const START_PRODUCTS_DOWNLOAD = 'START_PRODUCT_DOWNLOAD';
export const SUCCESS_PRODUCTS_DOWNLOAD = 'SUCCESS_PRODUCT_DOWNLOAD';
export const FAILURE_PRODUCTS_DOWNLOAD = 'FAILURE_PRODUCT_DOWNLOAD';