export const ADD_PRODUCT = 'ADD_PRODUCT';
export const SUCCESS_ADD_PRODUCT = 'SUCCESS_ADD_PRODUCT';
export const FAILURE_ADD_PRODUCT = 'FAILURE_ADD_PRODUCT';

export const START_PRODUCTS_DOWNLOAD = 'START_PRODUCTS_DOWNLOAD';
export const SUCCESS_PRODUCTS_DOWNLOAD = 'SUCCESS_PRODUCTS_DOWNLOAD';
export const FAILURE_PRODUCTS_DOWNLOAD = 'FAILURE_PRODUCTS_DOWNLOAD';

export const GET_PRODUCT_DELETE = 'GET_PRODUCT_DELETE';
export const SUCCESS_PRODUCT_DELETE = 'SUCCESS_PRODUCT_DELETE';
export const FAILURE_PRODUCT_DELETE = 'FAILURE_PRODUCT_DELETE';


export const GET_PRODUCT_EDIT = 'GET_PRODUCT_EDIT';
export const START_PRODUCT_EDIT = 'START_PRODUCT_EDIT';
export const SUCCESS_PRODUCT_EDIT = 'SUCCESS_PRODUCT_EDIT';
export const FAILURE_PRODUCT_EDIT = 'FAILURE_PRODUCT_EDIT';